### ISSUE TITLE
Some short forms are wrong for lib functions

### ISSUE THREAD

**Issue by figsoda** [nix-community/noogle#36] opened 2023-05-07 18:39 UTC
**What happened**
`lib.generators.toJSON`'s documentation says its short form is `lib.toJSON`, but they actually have different signatures
The same thing happens for functions like `lib.modules.importJSON`

**Steps to Reproduce**
1. search for `lib.generators.toJSON`
2. profit

**Expected behavior**
`lib.generators.toJSON` should not show a short form of `lib.toJSON`

**Screenshots**
![](https://user-images.githubusercontent.com/40620903/236696159-0d22b645-d582-4ed8-ad5a-79b5dd861219.png)

**Desktop (please complete the following information):**
 - OS: x86_64 NixOS
 - Browser: Firefox
 - Version: 112.0.2

**Comment by hsjobeki** [comment] 2023-05-07 18:46
@figsoda yes noogle currently expects every lib.x.y function to have an alias in lib.y 
But this i wrong for a small percentageof functions. The problem is, that we‘d have to dynamically evaluate to know exactly. 

Would you remove the alias field then? 

We have to wait for a dynamic implementation, which is under way, bit will take a few weeks/months before it is part of noogle.

> This is also Related to RFC-145

**Comment by figsoda** [comment] 2023-05-07 18:50
Either removing the alias field or manually keeping track of a list of false-positives sounds good to me

**Comment by hsjobeki** [comment] 2023-10-02 12:26
Made some progress on alias tracking. Could be merged in some weeks, but requires a patched version of nix itself.
-> Preview on: https://hsjobeki.github.io/nix-doc-comments/ (Some poc for the doc-comment rfc)

**Comment by hsjobeki** [comment] 2024-01-07 20:10
Resolved. https://noogle.dev/f/lib/generators/toJSON
Funny fact toYaml is an alias of toJson: https://github.com/hsjobeki/nixpkgs/blob/migrate-doc-comments/lib/generators.nix#L303
Which is correctly displayed now. :)

**Closed by hsjobeki** 2024-01-07 20:10 UTC
Labels: bug
